// The tagged template literal throws eslint indents off bad. Best to just disable it.
/* eslint indent: 'off' */
import AbilitiesStore from '~/Abilities.store';
import { itemList, applyItemLoadout } from '~/utilities/testHelpers';

describe('Ability to enter northeast Dark World:', () => {
	const items = applyItemLoadout(itemList);
	const store = AbilitiesStore.create({
		id: '1',
		config: '2',
	});

	store.hasItem = jest.fn().mockImplementation(name => items[name]);
	test.each`
		agahnimCheck | agahnim | canDefeatAgahnim | hammer | canLiftRocks | moonPearl | canLiftDarkRocks | canSwim | canAccessDarkWorldPortal | expected 
		${false} | ${false} | ${false} | ${false} | ${false} | ${false} | ${false} | ${false} | ${false} | ${false} 
		${false} | ${false} | ${true} | ${false} | ${false} | ${false} | ${false} | ${false} | ${false} | ${false} 
		${true} | ${false} | ${false} | ${false} | ${false} | ${false} | ${false} | ${false} | ${false} | ${false} 
		${false} | ${false} | ${false} | ${false} | ${true} | ${false} | ${false} | ${false} | ${false} | ${false} 
		${false} | ${false} | ${true} | ${false} | ${true} | ${false} | ${false} | ${false} | ${false} | ${false} 
		${true} | ${false} | ${false} | ${false} | ${true} | ${false} | ${false} | ${false} | ${false} | ${false} 
		${false} | ${false} | ${false} | ${true} | ${false} | ${false} | ${false} | ${false} | ${false} | ${false} 
		${false} | ${false} | ${true} | ${true} | ${false} | ${false} | ${false} | ${false} | ${false} | ${false} 
		${true} | ${false} | ${false} | ${true} | ${false} | ${false} | ${false} | ${false} | ${false} | ${false} 
		${false} | ${false} | ${false} | ${true} | ${true} | ${false} | ${false} | ${false} | ${false} | ${false} 
		${false} | ${false} | ${true} | ${true} | ${true} | ${false} | ${false} | ${false} | ${false} | ${false} 
		${true} | ${false} | ${false} | ${true} | ${true} | ${false} | ${false} | ${false} | ${false} | ${false} 
		${false} | ${false} | ${false} | ${false} | ${true} | ${false} | ${true} | ${false} | ${false} | ${false} 
		${false} | ${false} | ${true} | ${false} | ${true} | ${false} | ${true} | ${false} | ${false} | ${false} 
		${true} | ${false} | ${false} | ${false} | ${true} | ${false} | ${true} | ${false} | ${false} | ${false} 
		${false} | ${false} | ${false} | ${true} | ${true} | ${false} | ${true} | ${false} | ${false} | ${false} 
		${false} | ${false} | ${true} | ${true} | ${true} | ${false} | ${true} | ${false} | ${false} | ${false} 
		${true} | ${false} | ${false} | ${true} | ${true} | ${false} | ${true} | ${false} | ${false} | ${false} 
		${false} | ${false} | ${false} | ${false} | ${false} | ${true} | ${false} | ${false} | ${false} | ${false} 
		${false} | ${false} | ${true} | ${false} | ${false} | ${true} | ${false} | ${false} | ${false} | ${false} 
		${true} | ${false} | ${false} | ${false} | ${false} | ${true} | ${false} | ${false} | ${false} | ${false} 
		${false} | ${false} | ${false} | ${false} | ${true} | ${true} | ${false} | ${false} | ${false} | ${false} 
		${false} | ${false} | ${true} | ${false} | ${true} | ${true} | ${false} | ${false} | ${false} | ${false} 
		${true} | ${false} | ${false} | ${false} | ${true} | ${true} | ${false} | ${false} | ${false} | ${false} 
		${false} | ${false} | ${false} | ${true} | ${false} | ${true} | ${false} | ${false} | ${false} | ${false} 
		${false} | ${false} | ${true} | ${true} | ${false} | ${true} | ${false} | ${false} | ${false} | ${false} 
		${true} | ${false} | ${false} | ${true} | ${false} | ${true} | ${false} | ${false} | ${false} | ${false} 
		${false} | ${false} | ${false} | ${false} | ${true} | ${true} | ${true} | ${false} | ${false} | ${false} 
		${false} | ${false} | ${true} | ${false} | ${true} | ${true} | ${true} | ${false} | ${false} | ${false} 
		${true} | ${false} | ${false} | ${false} | ${true} | ${true} | ${true} | ${false} | ${false} | ${false} 
		${false} | ${false} | ${false} | ${false} | ${false} | ${false} | ${false} | ${true} | ${false} | ${false} 
		${false} | ${false} | ${true} | ${false} | ${false} | ${false} | ${false} | ${true} | ${false} | ${false} 
		${true} | ${false} | ${false} | ${false} | ${false} | ${false} | ${false} | ${true} | ${false} | ${false} 
		${false} | ${false} | ${false} | ${false} | ${true} | ${false} | ${false} | ${true} | ${false} | ${false} 
		${false} | ${false} | ${true} | ${false} | ${true} | ${false} | ${false} | ${true} | ${false} | ${false} 
		${true} | ${false} | ${false} | ${false} | ${true} | ${false} | ${false} | ${true} | ${false} | ${false} 
		${false} | ${false} | ${false} | ${true} | ${false} | ${false} | ${false} | ${true} | ${false} | ${false} 
		${false} | ${false} | ${true} | ${true} | ${false} | ${false} | ${false} | ${true} | ${false} | ${false} 
		${true} | ${false} | ${false} | ${true} | ${false} | ${false} | ${false} | ${true} | ${false} | ${false} 
		${false} | ${false} | ${false} | ${true} | ${true} | ${false} | ${false} | ${true} | ${false} | ${false} 
		${false} | ${false} | ${true} | ${true} | ${true} | ${false} | ${false} | ${true} | ${false} | ${false} 
		${true} | ${false} | ${false} | ${true} | ${true} | ${false} | ${false} | ${true} | ${false} | ${false} 
		${false} | ${false} | ${false} | ${false} | ${true} | ${false} | ${true} | ${true} | ${false} | ${false} 
		${false} | ${false} | ${true} | ${false} | ${true} | ${false} | ${true} | ${true} | ${false} | ${false} 
		${true} | ${false} | ${false} | ${false} | ${true} | ${false} | ${true} | ${true} | ${false} | ${false} 
		${false} | ${false} | ${false} | ${true} | ${true} | ${false} | ${true} | ${true} | ${false} | ${false} 
		${false} | ${false} | ${true} | ${true} | ${true} | ${false} | ${true} | ${true} | ${false} | ${false} 
		${true} | ${false} | ${false} | ${true} | ${true} | ${false} | ${true} | ${true} | ${false} | ${false} 
		${false} | ${false} | ${false} | ${false} | ${false} | ${true} | ${false} | ${true} | ${false} | ${false} 
		${false} | ${false} | ${true} | ${false} | ${false} | ${true} | ${false} | ${true} | ${false} | ${false} 
		${true} | ${false} | ${false} | ${false} | ${false} | ${true} | ${false} | ${true} | ${false} | ${false} 
		${false} | ${false} | ${false} | ${false} | ${true} | ${true} | ${false} | ${true} | ${false} | ${false} 
		${false} | ${false} | ${true} | ${false} | ${true} | ${true} | ${false} | ${true} | ${false} | ${false} 
		${true} | ${false} | ${false} | ${false} | ${true} | ${true} | ${false} | ${true} | ${false} | ${false} 
		${false} | ${false} | ${false} | ${true} | ${false} | ${true} | ${false} | ${true} | ${false} | ${false} 
		${false} | ${false} | ${true} | ${true} | ${false} | ${true} | ${false} | ${true} | ${false} | ${false} 
		${true} | ${false} | ${false} | ${true} | ${false} | ${true} | ${false} | ${true} | ${false} | ${false} 
		${false} | ${false} | ${false} | ${false} | ${false} | ${false} | ${false} | ${false} | ${true} | ${false} 
		${false} | ${false} | ${true} | ${false} | ${false} | ${false} | ${false} | ${false} | ${true} | ${false} 
		${true} | ${false} | ${false} | ${false} | ${false} | ${false} | ${false} | ${false} | ${true} | ${false} 
		${false} | ${false} | ${false} | ${false} | ${true} | ${false} | ${false} | ${false} | ${true} | ${false} 
		${false} | ${false} | ${true} | ${false} | ${true} | ${false} | ${false} | ${false} | ${true} | ${false} 
		${true} | ${false} | ${false} | ${false} | ${true} | ${false} | ${false} | ${false} | ${true} | ${false} 
		${false} | ${false} | ${false} | ${true} | ${false} | ${false} | ${false} | ${false} | ${true} | ${false} 
		${false} | ${false} | ${true} | ${true} | ${false} | ${false} | ${false} | ${false} | ${true} | ${false} 
		${true} | ${false} | ${false} | ${true} | ${false} | ${false} | ${false} | ${false} | ${true} | ${false} 
		${false} | ${false} | ${false} | ${true} | ${true} | ${false} | ${false} | ${false} | ${true} | ${false} 
		${false} | ${false} | ${true} | ${true} | ${true} | ${false} | ${false} | ${false} | ${true} | ${false} 
		${true} | ${false} | ${false} | ${true} | ${true} | ${false} | ${false} | ${false} | ${true} | ${false} 
		${false} | ${false} | ${false} | ${false} | ${true} | ${false} | ${true} | ${false} | ${true} | ${false} 
		${false} | ${false} | ${true} | ${false} | ${true} | ${false} | ${true} | ${false} | ${true} | ${false} 
		${true} | ${false} | ${false} | ${false} | ${true} | ${false} | ${true} | ${false} | ${true} | ${false} 
		${false} | ${false} | ${false} | ${true} | ${true} | ${false} | ${true} | ${false} | ${true} | ${false} 
		${false} | ${false} | ${true} | ${true} | ${true} | ${false} | ${true} | ${false} | ${true} | ${false} 
		${true} | ${false} | ${false} | ${true} | ${true} | ${false} | ${true} | ${false} | ${true} | ${false} 
		${false} | ${false} | ${false} | ${false} | ${false} | ${true} | ${false} | ${false} | ${true} | ${false} 
		${false} | ${false} | ${true} | ${false} | ${false} | ${true} | ${false} | ${false} | ${true} | ${false} 
		${true} | ${false} | ${false} | ${false} | ${false} | ${true} | ${false} | ${false} | ${true} | ${false} 
		${false} | ${false} | ${false} | ${false} | ${true} | ${true} | ${false} | ${false} | ${true} | ${false} 
		${false} | ${false} | ${true} | ${false} | ${true} | ${true} | ${false} | ${false} | ${true} | ${false} 
		${true} | ${false} | ${false} | ${false} | ${true} | ${true} | ${false} | ${false} | ${true} | ${false} 
		${false} | ${false} | ${false} | ${true} | ${false} | ${true} | ${false} | ${false} | ${true} | ${false} 
		${false} | ${false} | ${true} | ${true} | ${false} | ${true} | ${false} | ${false} | ${true} | ${false} 
		${true} | ${false} | ${false} | ${true} | ${false} | ${true} | ${false} | ${false} | ${true} | ${false} 
		${false} | ${false} | ${false} | ${false} | ${true} | ${true} | ${true} | ${false} | ${true} | ${false} 
		${false} | ${false} | ${true} | ${false} | ${true} | ${true} | ${true} | ${false} | ${true} | ${false} 
		${true} | ${false} | ${false} | ${false} | ${true} | ${true} | ${true} | ${false} | ${true} | ${false} 
		${false} | ${false} | ${false} | ${false} | ${false} | ${false} | ${false} | ${true} | ${true} | ${false} 
		${false} | ${false} | ${true} | ${false} | ${false} | ${false} | ${false} | ${true} | ${true} | ${false} 
		${true} | ${false} | ${false} | ${false} | ${false} | ${false} | ${false} | ${true} | ${true} | ${false} 
		${false} | ${false} | ${false} | ${false} | ${true} | ${false} | ${false} | ${true} | ${true} | ${false} 
		${false} | ${false} | ${true} | ${false} | ${true} | ${false} | ${false} | ${true} | ${true} | ${false} 
		${true} | ${false} | ${false} | ${false} | ${true} | ${false} | ${false} | ${true} | ${true} | ${false} 
		${false} | ${false} | ${false} | ${true} | ${false} | ${false} | ${false} | ${true} | ${true} | ${false} 
		${false} | ${false} | ${true} | ${true} | ${false} | ${false} | ${false} | ${true} | ${true} | ${false} 
		${true} | ${false} | ${false} | ${true} | ${false} | ${false} | ${false} | ${true} | ${true} | ${false} 
		${false} | ${false} | ${false} | ${true} | ${true} | ${false} | ${false} | ${true} | ${true} | ${false} 
		${false} | ${false} | ${true} | ${true} | ${true} | ${false} | ${false} | ${true} | ${true} | ${false} 
		${true} | ${false} | ${false} | ${true} | ${true} | ${false} | ${false} | ${true} | ${true} | ${false} 
		${false} | ${false} | ${false} | ${false} | ${true} | ${false} | ${true} | ${true} | ${true} | ${false} 
		${false} | ${false} | ${true} | ${false} | ${true} | ${false} | ${true} | ${true} | ${true} | ${false} 
		${true} | ${false} | ${false} | ${false} | ${true} | ${false} | ${true} | ${true} | ${true} | ${false} 
		${false} | ${false} | ${false} | ${true} | ${true} | ${false} | ${true} | ${true} | ${true} | ${false} 
		${false} | ${false} | ${true} | ${true} | ${true} | ${false} | ${true} | ${true} | ${true} | ${false} 
		${true} | ${false} | ${false} | ${true} | ${true} | ${false} | ${true} | ${true} | ${true} | ${false} 
		${false} | ${false} | ${false} | ${false} | ${false} | ${true} | ${false} | ${true} | ${true} | ${true} 
		${false} | ${false} | ${true} | ${false} | ${false} | ${true} | ${false} | ${true} | ${true} | ${true} 
		${true} | ${false} | ${false} | ${false} | ${false} | ${true} | ${false} | ${true} | ${true} | ${true} 
		${false} | ${false} | ${false} | ${false} | ${true} | ${true} | ${false} | ${true} | ${true} | ${true} 
		${false} | ${false} | ${true} | ${false} | ${true} | ${true} | ${false} | ${true} | ${true} | ${true} 
		${true} | ${false} | ${false} | ${false} | ${true} | ${true} | ${false} | ${true} | ${true} | ${true} 
		${false} | ${false} | ${false} | ${true} | ${false} | ${true} | ${false} | ${true} | ${true} | ${true} 
		${false} | ${false} | ${true} | ${true} | ${false} | ${true} | ${false} | ${true} | ${true} | ${true} 
		${true} | ${false} | ${false} | ${true} | ${false} | ${true} | ${false} | ${true} | ${true} | ${true} 
		${false} | ${false} | ${false} | ${false} | ${true} | ${true} | ${true} | ${true} | ${true} | ${true} 
		${false} | ${false} | ${false} | ${false} | ${true} | ${true} | ${true} | ${true} | ${false} | ${true} 
		${false} | ${false} | ${true} | ${false} | ${true} | ${true} | ${true} | ${true} | ${true} | ${true} 
		${false} | ${false} | ${true} | ${false} | ${true} | ${true} | ${true} | ${true} | ${false} | ${true} 
		${true} | ${false} | ${false} | ${false} | ${true} | ${true} | ${true} | ${true} | ${true} | ${true} 
		${true} | ${false} | ${false} | ${false} | ${true} | ${true} | ${true} | ${true} | ${false} | ${true} 
		${false} | ${false} | ${false} | ${true} | ${true} | ${true} | ${false} | ${true} | ${true} | ${true} 
		${false} | ${false} | ${false} | ${true} | ${true} | ${true} | ${false} | ${true} | ${false} | ${true} 
		${false} | ${false} | ${false} | ${true} | ${true} | ${true} | ${false} | ${false} | ${true} | ${true} 
		${false} | ${false} | ${false} | ${true} | ${true} | ${true} | ${false} | ${false} | ${false} | ${true} 
		${false} | ${false} | ${false} | ${true} | ${true} | ${true} | ${true} | ${true} | ${true} | ${true} 
		${false} | ${false} | ${false} | ${true} | ${true} | ${true} | ${true} | ${true} | ${false} | ${true} 
		${false} | ${false} | ${false} | ${true} | ${true} | ${true} | ${true} | ${false} | ${true} | ${true} 
		${false} | ${false} | ${false} | ${true} | ${true} | ${true} | ${true} | ${false} | ${false} | ${true} 
		${false} | ${false} | ${true} | ${true} | ${true} | ${true} | ${false} | ${true} | ${true} | ${true} 
		${false} | ${false} | ${true} | ${true} | ${true} | ${true} | ${false} | ${true} | ${false} | ${true} 
		${false} | ${false} | ${true} | ${true} | ${true} | ${true} | ${false} | ${false} | ${true} | ${true} 
		${false} | ${false} | ${true} | ${true} | ${true} | ${true} | ${false} | ${false} | ${false} | ${true} 
		${false} | ${false} | ${true} | ${true} | ${true} | ${true} | ${true} | ${true} | ${true} | ${true} 
		${false} | ${false} | ${true} | ${true} | ${true} | ${true} | ${true} | ${true} | ${false} | ${true} 
		${false} | ${false} | ${true} | ${true} | ${true} | ${true} | ${true} | ${false} | ${true} | ${true} 
		${false} | ${false} | ${true} | ${true} | ${true} | ${true} | ${true} | ${false} | ${false} | ${true} 
		${true} | ${false} | ${false} | ${true} | ${true} | ${true} | ${false} | ${true} | ${true} | ${true} 
		${true} | ${false} | ${false} | ${true} | ${true} | ${true} | ${false} | ${true} | ${false} | ${true} 
		${true} | ${false} | ${false} | ${true} | ${true} | ${true} | ${false} | ${false} | ${true} | ${true} 
		${true} | ${false} | ${false} | ${true} | ${true} | ${true} | ${false} | ${false} | ${false} | ${true} 
		${true} | ${false} | ${false} | ${true} | ${true} | ${true} | ${true} | ${true} | ${true} | ${true} 
		${true} | ${false} | ${false} | ${true} | ${true} | ${true} | ${true} | ${true} | ${false} | ${true} 
		${true} | ${false} | ${false} | ${true} | ${true} | ${true} | ${true} | ${false} | ${true} | ${true} 
		${true} | ${false} | ${false} | ${true} | ${true} | ${true} | ${true} | ${false} | ${false} | ${true} 
		${true} | ${false} | ${true} | ${true} | ${false} | ${true} | ${false} | ${true} | ${true} | ${true} 
		${true} | ${false} | ${true} | ${true} | ${false} | ${true} | ${false} | ${true} | ${false} | ${true} 
		${true} | ${false} | ${true} | ${true} | ${false} | ${true} | ${false} | ${false} | ${true} | ${true} 
		${true} | ${false} | ${true} | ${true} | ${false} | ${true} | ${false} | ${false} | ${false} | ${true} 
		${true} | ${false} | ${true} | ${true} | ${false} | ${false} | ${false} | ${true} | ${true} | ${true} 
		${true} | ${false} | ${true} | ${true} | ${false} | ${false} | ${false} | ${true} | ${false} | ${true} 
		${true} | ${false} | ${true} | ${true} | ${false} | ${false} | ${false} | ${false} | ${true} | ${true} 
		${true} | ${false} | ${true} | ${true} | ${false} | ${false} | ${false} | ${false} | ${false} | ${true} 
		${true} | ${false} | ${true} | ${false} | ${false} | ${true} | ${false} | ${true} | ${true} | ${true} 
		${true} | ${false} | ${true} | ${false} | ${false} | ${true} | ${false} | ${true} | ${false} | ${true} 
		${true} | ${false} | ${true} | ${false} | ${false} | ${true} | ${false} | ${false} | ${true} | ${true} 
		${true} | ${false} | ${true} | ${false} | ${false} | ${true} | ${false} | ${false} | ${false} | ${true} 
		${true} | ${false} | ${true} | ${false} | ${false} | ${false} | ${false} | ${true} | ${true} | ${true} 
		${true} | ${false} | ${true} | ${false} | ${false} | ${false} | ${false} | ${true} | ${false} | ${true} 
		${true} | ${false} | ${true} | ${false} | ${false} | ${false} | ${false} | ${false} | ${true} | ${true} 
		${true} | ${false} | ${true} | ${false} | ${false} | ${false} | ${false} | ${false} | ${false} | ${true} 
		${true} | ${false} | ${true} | ${true} | ${true} | ${true} | ${false} | ${true} | ${true} | ${true} 
		${true} | ${false} | ${true} | ${true} | ${true} | ${true} | ${false} | ${true} | ${false} | ${true} 
		${true} | ${false} | ${true} | ${true} | ${true} | ${true} | ${false} | ${false} | ${true} | ${true} 
		${true} | ${false} | ${true} | ${true} | ${true} | ${true} | ${false} | ${false} | ${false} | ${true} 
		${true} | ${false} | ${true} | ${true} | ${true} | ${false} | ${false} | ${true} | ${true} | ${true} 
		${true} | ${false} | ${true} | ${true} | ${true} | ${false} | ${false} | ${true} | ${false} | ${true} 
		${true} | ${false} | ${true} | ${true} | ${true} | ${false} | ${false} | ${false} | ${true} | ${true} 
		${true} | ${false} | ${true} | ${true} | ${true} | ${false} | ${false} | ${false} | ${false} | ${true} 
		${true} | ${false} | ${true} | ${false} | ${true} | ${true} | ${false} | ${true} | ${true} | ${true} 
		${true} | ${false} | ${true} | ${false} | ${true} | ${true} | ${false} | ${true} | ${false} | ${true} 
		${true} | ${false} | ${true} | ${false} | ${true} | ${true} | ${false} | ${false} | ${true} | ${true} 
		${true} | ${false} | ${true} | ${false} | ${true} | ${true} | ${false} | ${false} | ${false} | ${true} 
		${true} | ${false} | ${true} | ${false} | ${true} | ${false} | ${false} | ${true} | ${true} | ${true} 
		${true} | ${false} | ${true} | ${false} | ${true} | ${false} | ${false} | ${true} | ${false} | ${true} 
		${true} | ${false} | ${true} | ${false} | ${true} | ${false} | ${false} | ${false} | ${true} | ${true} 
		${true} | ${false} | ${true} | ${false} | ${true} | ${false} | ${false} | ${false} | ${false} | ${true} 
		${true} | ${false} | ${true} | ${true} | ${true} | ${true} | ${true} | ${true} | ${true} | ${true} 
		${true} | ${false} | ${true} | ${true} | ${true} | ${true} | ${true} | ${true} | ${false} | ${true} 
		${true} | ${false} | ${true} | ${true} | ${true} | ${true} | ${true} | ${false} | ${true} | ${true} 
		${true} | ${false} | ${true} | ${true} | ${true} | ${true} | ${true} | ${false} | ${false} | ${true} 
		${true} | ${false} | ${true} | ${true} | ${true} | ${false} | ${true} | ${true} | ${true} | ${true} 
		${true} | ${false} | ${true} | ${true} | ${true} | ${false} | ${true} | ${true} | ${false} | ${true} 
		${true} | ${false} | ${true} | ${true} | ${true} | ${false} | ${true} | ${false} | ${true} | ${true} 
		${true} | ${false} | ${true} | ${true} | ${true} | ${false} | ${true} | ${false} | ${false} | ${true} 
		${true} | ${false} | ${true} | ${false} | ${true} | ${true} | ${true} | ${true} | ${true} | ${true} 
		${true} | ${false} | ${true} | ${false} | ${true} | ${true} | ${true} | ${true} | ${false} | ${true} 
		${true} | ${false} | ${true} | ${false} | ${true} | ${true} | ${true} | ${false} | ${true} | ${true} 
		${true} | ${false} | ${true} | ${false} | ${true} | ${true} | ${true} | ${false} | ${false} | ${true} 
		${true} | ${false} | ${true} | ${false} | ${true} | ${false} | ${true} | ${true} | ${true} | ${true} 
		${true} | ${false} | ${true} | ${false} | ${true} | ${false} | ${true} | ${true} | ${false} | ${true} 
		${true} | ${false} | ${true} | ${false} | ${true} | ${false} | ${true} | ${false} | ${true} | ${true} 
		${true} | ${false} | ${true} | ${false} | ${true} | ${false} | ${true} | ${false} | ${false} | ${true} 
		${true} | ${true} | ${true} | ${true} | ${false} | ${true} | ${false} | ${true} | ${true} | ${true} 
		${true} | ${true} | ${true} | ${true} | ${false} | ${true} | ${false} | ${true} | ${false} | ${true} 
		${true} | ${true} | ${true} | ${true} | ${false} | ${true} | ${false} | ${false} | ${true} | ${true} 
		${true} | ${true} | ${true} | ${true} | ${false} | ${true} | ${false} | ${false} | ${false} | ${true} 
		${true} | ${true} | ${true} | ${true} | ${false} | ${false} | ${false} | ${true} | ${true} | ${true} 
		${true} | ${true} | ${true} | ${true} | ${false} | ${false} | ${false} | ${true} | ${false} | ${true} 
		${true} | ${true} | ${true} | ${true} | ${false} | ${false} | ${false} | ${false} | ${true} | ${true} 
		${true} | ${true} | ${true} | ${true} | ${false} | ${false} | ${false} | ${false} | ${false} | ${true} 
		${true} | ${true} | ${true} | ${false} | ${false} | ${true} | ${false} | ${true} | ${true} | ${true} 
		${true} | ${true} | ${true} | ${false} | ${false} | ${true} | ${false} | ${true} | ${false} | ${true} 
		${true} | ${true} | ${true} | ${false} | ${false} | ${true} | ${false} | ${false} | ${true} | ${true} 
		${true} | ${true} | ${true} | ${false} | ${false} | ${true} | ${false} | ${false} | ${false} | ${true} 
		${true} | ${true} | ${true} | ${false} | ${false} | ${false} | ${false} | ${true} | ${true} | ${true} 
		${true} | ${true} | ${true} | ${false} | ${false} | ${false} | ${false} | ${true} | ${false} | ${true} 
		${true} | ${true} | ${true} | ${false} | ${false} | ${false} | ${false} | ${false} | ${true} | ${true} 
		${true} | ${true} | ${true} | ${false} | ${false} | ${false} | ${false} | ${false} | ${false} | ${true} 
		${true} | ${true} | ${false} | ${true} | ${false} | ${true} | ${false} | ${true} | ${true} | ${true} 
		${true} | ${true} | ${false} | ${true} | ${false} | ${true} | ${false} | ${true} | ${false} | ${true} 
		${true} | ${true} | ${false} | ${true} | ${false} | ${true} | ${false} | ${false} | ${true} | ${true} 
		${true} | ${true} | ${false} | ${true} | ${false} | ${true} | ${false} | ${false} | ${false} | ${true} 
		${true} | ${true} | ${false} | ${true} | ${false} | ${false} | ${false} | ${true} | ${true} | ${true} 
		${true} | ${true} | ${false} | ${true} | ${false} | ${false} | ${false} | ${true} | ${false} | ${true} 
		${true} | ${true} | ${false} | ${true} | ${false} | ${false} | ${false} | ${false} | ${true} | ${true} 
		${true} | ${true} | ${false} | ${true} | ${false} | ${false} | ${false} | ${false} | ${false} | ${true} 
		${true} | ${true} | ${false} | ${false} | ${false} | ${true} | ${false} | ${true} | ${true} | ${true} 
		${true} | ${true} | ${false} | ${false} | ${false} | ${true} | ${false} | ${true} | ${false} | ${true} 
		${true} | ${true} | ${false} | ${false} | ${false} | ${true} | ${false} | ${false} | ${true} | ${true} 
		${true} | ${true} | ${false} | ${false} | ${false} | ${true} | ${false} | ${false} | ${false} | ${true} 
		${true} | ${true} | ${false} | ${false} | ${false} | ${false} | ${false} | ${true} | ${true} | ${true} 
		${true} | ${true} | ${false} | ${false} | ${false} | ${false} | ${false} | ${true} | ${false} | ${true} 
		${true} | ${true} | ${false} | ${false} | ${false} | ${false} | ${false} | ${false} | ${true} | ${true} 
		${true} | ${true} | ${false} | ${false} | ${false} | ${false} | ${false} | ${false} | ${false} | ${true} 
		${false} | ${true} | ${true} | ${true} | ${false} | ${true} | ${false} | ${true} | ${true} | ${true} 
		${false} | ${true} | ${true} | ${true} | ${false} | ${true} | ${false} | ${true} | ${false} | ${true} 
		${false} | ${true} | ${true} | ${true} | ${false} | ${true} | ${false} | ${false} | ${true} | ${true} 
		${false} | ${true} | ${true} | ${true} | ${false} | ${true} | ${false} | ${false} | ${false} | ${true} 
		${false} | ${true} | ${true} | ${true} | ${false} | ${false} | ${false} | ${true} | ${true} | ${true} 
		${false} | ${true} | ${true} | ${true} | ${false} | ${false} | ${false} | ${true} | ${false} | ${true} 
		${false} | ${true} | ${true} | ${true} | ${false} | ${false} | ${false} | ${false} | ${true} | ${true} 
		${false} | ${true} | ${true} | ${true} | ${false} | ${false} | ${false} | ${false} | ${false} | ${true} 
		${false} | ${true} | ${true} | ${false} | ${false} | ${true} | ${false} | ${true} | ${true} | ${true} 
		${false} | ${true} | ${true} | ${false} | ${false} | ${true} | ${false} | ${true} | ${false} | ${true} 
		${false} | ${true} | ${true} | ${false} | ${false} | ${true} | ${false} | ${false} | ${true} | ${true} 
		${false} | ${true} | ${true} | ${false} | ${false} | ${true} | ${false} | ${false} | ${false} | ${true} 
		${false} | ${true} | ${true} | ${false} | ${false} | ${false} | ${false} | ${true} | ${true} | ${true} 
		${false} | ${true} | ${true} | ${false} | ${false} | ${false} | ${false} | ${true} | ${false} | ${true} 
		${false} | ${true} | ${true} | ${false} | ${false} | ${false} | ${false} | ${false} | ${true} | ${true} 
		${false} | ${true} | ${true} | ${false} | ${false} | ${false} | ${false} | ${false} | ${false} | ${true} 
		${false} | ${true} | ${false} | ${true} | ${false} | ${true} | ${false} | ${true} | ${true} | ${true} 
		${false} | ${true} | ${false} | ${true} | ${false} | ${true} | ${false} | ${true} | ${false} | ${true} 
		${false} | ${true} | ${false} | ${true} | ${false} | ${true} | ${false} | ${false} | ${true} | ${true} 
		${false} | ${true} | ${false} | ${true} | ${false} | ${true} | ${false} | ${false} | ${false} | ${true} 
		${false} | ${true} | ${false} | ${true} | ${false} | ${false} | ${false} | ${true} | ${true} | ${true} 
		${false} | ${true} | ${false} | ${true} | ${false} | ${false} | ${false} | ${true} | ${false} | ${true} 
		${false} | ${true} | ${false} | ${true} | ${false} | ${false} | ${false} | ${false} | ${true} | ${true} 
		${false} | ${true} | ${false} | ${true} | ${false} | ${false} | ${false} | ${false} | ${false} | ${true} 
		${false} | ${true} | ${false} | ${false} | ${false} | ${true} | ${false} | ${true} | ${true} | ${true} 
		${false} | ${true} | ${false} | ${false} | ${false} | ${true} | ${false} | ${true} | ${false} | ${true} 
		${false} | ${true} | ${false} | ${false} | ${false} | ${true} | ${false} | ${false} | ${true} | ${true} 
		${false} | ${true} | ${false} | ${false} | ${false} | ${true} | ${false} | ${false} | ${false} | ${true} 
		${false} | ${true} | ${false} | ${false} | ${false} | ${false} | ${false} | ${true} | ${true} | ${true} 
		${false} | ${true} | ${false} | ${false} | ${false} | ${false} | ${false} | ${true} | ${false} | ${true} 
		${false} | ${true} | ${false} | ${false} | ${false} | ${false} | ${false} | ${false} | ${true} | ${true} 
		${false} | ${true} | ${false} | ${false} | ${false} | ${false} | ${false} | ${false} | ${false} | ${true} 
		${true} | ${true} | ${true} | ${true} | ${true} | ${true} | ${false} | ${true} | ${true} | ${true} 
		${true} | ${true} | ${true} | ${true} | ${true} | ${true} | ${false} | ${true} | ${false} | ${true} 
		${true} | ${true} | ${true} | ${true} | ${true} | ${true} | ${false} | ${false} | ${true} | ${true} 
		${true} | ${true} | ${true} | ${true} | ${true} | ${true} | ${false} | ${false} | ${false} | ${true} 
		${true} | ${true} | ${true} | ${true} | ${true} | ${false} | ${false} | ${true} | ${true} | ${true} 
		${true} | ${true} | ${true} | ${true} | ${true} | ${false} | ${false} | ${true} | ${false} | ${true} 
		${true} | ${true} | ${true} | ${true} | ${true} | ${false} | ${false} | ${false} | ${true} | ${true} 
		${true} | ${true} | ${true} | ${true} | ${true} | ${false} | ${false} | ${false} | ${false} | ${true} 
		${true} | ${true} | ${true} | ${false} | ${true} | ${true} | ${false} | ${true} | ${true} | ${true} 
		${true} | ${true} | ${true} | ${false} | ${true} | ${true} | ${false} | ${true} | ${false} | ${true} 
		${true} | ${true} | ${true} | ${false} | ${true} | ${true} | ${false} | ${false} | ${true} | ${true} 
		${true} | ${true} | ${true} | ${false} | ${true} | ${true} | ${false} | ${false} | ${false} | ${true} 
		${true} | ${true} | ${true} | ${false} | ${true} | ${false} | ${false} | ${true} | ${true} | ${true} 
		${true} | ${true} | ${true} | ${false} | ${true} | ${false} | ${false} | ${true} | ${false} | ${true} 
		${true} | ${true} | ${true} | ${false} | ${true} | ${false} | ${false} | ${false} | ${true} | ${true} 
		${true} | ${true} | ${true} | ${false} | ${true} | ${false} | ${false} | ${false} | ${false} | ${true} 
		${true} | ${true} | ${false} | ${true} | ${true} | ${true} | ${false} | ${true} | ${true} | ${true} 
		${true} | ${true} | ${false} | ${true} | ${true} | ${true} | ${false} | ${true} | ${false} | ${true} 
		${true} | ${true} | ${false} | ${true} | ${true} | ${true} | ${false} | ${false} | ${true} | ${true} 
		${true} | ${true} | ${false} | ${true} | ${true} | ${true} | ${false} | ${false} | ${false} | ${true} 
		${true} | ${true} | ${false} | ${true} | ${true} | ${false} | ${false} | ${true} | ${true} | ${true} 
		${true} | ${true} | ${false} | ${true} | ${true} | ${false} | ${false} | ${true} | ${false} | ${true} 
		${true} | ${true} | ${false} | ${true} | ${true} | ${false} | ${false} | ${false} | ${true} | ${true} 
		${true} | ${true} | ${false} | ${true} | ${true} | ${false} | ${false} | ${false} | ${false} | ${true} 
		${true} | ${true} | ${false} | ${false} | ${true} | ${true} | ${false} | ${true} | ${true} | ${true} 
		${true} | ${true} | ${false} | ${false} | ${true} | ${true} | ${false} | ${true} | ${false} | ${true} 
		${true} | ${true} | ${false} | ${false} | ${true} | ${true} | ${false} | ${false} | ${true} | ${true} 
		${true} | ${true} | ${false} | ${false} | ${true} | ${true} | ${false} | ${false} | ${false} | ${true} 
		${true} | ${true} | ${false} | ${false} | ${true} | ${false} | ${false} | ${true} | ${true} | ${true} 
		${true} | ${true} | ${false} | ${false} | ${true} | ${false} | ${false} | ${true} | ${false} | ${true} 
		${true} | ${true} | ${false} | ${false} | ${true} | ${false} | ${false} | ${false} | ${true} | ${true} 
		${true} | ${true} | ${false} | ${false} | ${true} | ${false} | ${false} | ${false} | ${false} | ${true} 
		${false} | ${true} | ${true} | ${true} | ${true} | ${true} | ${false} | ${true} | ${true} | ${true} 
		${false} | ${true} | ${true} | ${true} | ${true} | ${true} | ${false} | ${true} | ${false} | ${true} 
		${false} | ${true} | ${true} | ${true} | ${true} | ${true} | ${false} | ${false} | ${true} | ${true} 
		${false} | ${true} | ${true} | ${true} | ${true} | ${true} | ${false} | ${false} | ${false} | ${true} 
		${false} | ${true} | ${true} | ${true} | ${true} | ${false} | ${false} | ${true} | ${true} | ${true} 
		${false} | ${true} | ${true} | ${true} | ${true} | ${false} | ${false} | ${true} | ${false} | ${true} 
		${false} | ${true} | ${true} | ${true} | ${true} | ${false} | ${false} | ${false} | ${true} | ${true} 
		${false} | ${true} | ${true} | ${true} | ${true} | ${false} | ${false} | ${false} | ${false} | ${true} 
		${false} | ${true} | ${true} | ${false} | ${true} | ${true} | ${false} | ${true} | ${true} | ${true} 
		${false} | ${true} | ${true} | ${false} | ${true} | ${true} | ${false} | ${true} | ${false} | ${true} 
		${false} | ${true} | ${true} | ${false} | ${true} | ${true} | ${false} | ${false} | ${true} | ${true} 
		${false} | ${true} | ${true} | ${false} | ${true} | ${true} | ${false} | ${false} | ${false} | ${true} 
		${false} | ${true} | ${true} | ${false} | ${true} | ${false} | ${false} | ${true} | ${true} | ${true} 
		${false} | ${true} | ${true} | ${false} | ${true} | ${false} | ${false} | ${true} | ${false} | ${true} 
		${false} | ${true} | ${true} | ${false} | ${true} | ${false} | ${false} | ${false} | ${true} | ${true} 
		${false} | ${true} | ${true} | ${false} | ${true} | ${false} | ${false} | ${false} | ${false} | ${true} 
		${false} | ${true} | ${false} | ${true} | ${true} | ${true} | ${false} | ${true} | ${true} | ${true} 
		${false} | ${true} | ${false} | ${true} | ${true} | ${true} | ${false} | ${true} | ${false} | ${true} 
		${false} | ${true} | ${false} | ${true} | ${true} | ${true} | ${false} | ${false} | ${true} | ${true} 
		${false} | ${true} | ${false} | ${true} | ${true} | ${true} | ${false} | ${false} | ${false} | ${true} 
		${false} | ${true} | ${false} | ${true} | ${true} | ${false} | ${false} | ${true} | ${true} | ${true} 
		${false} | ${true} | ${false} | ${true} | ${true} | ${false} | ${false} | ${true} | ${false} | ${true} 
		${false} | ${true} | ${false} | ${true} | ${true} | ${false} | ${false} | ${false} | ${true} | ${true} 
		${false} | ${true} | ${false} | ${true} | ${true} | ${false} | ${false} | ${false} | ${false} | ${true} 
		${false} | ${true} | ${false} | ${false} | ${true} | ${true} | ${false} | ${true} | ${true} | ${true} 
		${false} | ${true} | ${false} | ${false} | ${true} | ${true} | ${false} | ${true} | ${false} | ${true} 
		${false} | ${true} | ${false} | ${false} | ${true} | ${true} | ${false} | ${false} | ${true} | ${true} 
		${false} | ${true} | ${false} | ${false} | ${true} | ${true} | ${false} | ${false} | ${false} | ${true} 
		${false} | ${true} | ${false} | ${false} | ${true} | ${false} | ${false} | ${true} | ${true} | ${true} 
		${false} | ${true} | ${false} | ${false} | ${true} | ${false} | ${false} | ${true} | ${false} | ${true} 
		${false} | ${true} | ${false} | ${false} | ${true} | ${false} | ${false} | ${false} | ${true} | ${true} 
		${false} | ${true} | ${false} | ${false} | ${true} | ${false} | ${false} | ${false} | ${false} | ${true} 
		${true} | ${true} | ${true} | ${true} | ${true} | ${true} | ${true} | ${true} | ${false} | ${true} 
		${true} | ${true} | ${true} | ${true} | ${true} | ${true} | ${true} | ${false} | ${true} | ${true} 
		${true} | ${true} | ${true} | ${true} | ${true} | ${true} | ${true} | ${false} | ${false} | ${true} 
		${true} | ${true} | ${true} | ${true} | ${true} | ${false} | ${true} | ${true} | ${true} | ${true} 
		${true} | ${true} | ${true} | ${true} | ${true} | ${false} | ${true} | ${true} | ${false} | ${true} 
		${true} | ${true} | ${true} | ${true} | ${true} | ${false} | ${true} | ${false} | ${true} | ${true} 
		${true} | ${true} | ${true} | ${true} | ${true} | ${false} | ${true} | ${false} | ${false} | ${true} 
		${true} | ${true} | ${true} | ${true} | ${true} | ${true} | ${true} | ${true} | ${true} | ${true} 
		${true} | ${true} | ${true} | ${false} | ${true} | ${true} | ${true} | ${true} | ${true} | ${true} 
		${true} | ${true} | ${true} | ${false} | ${true} | ${true} | ${true} | ${true} | ${false} | ${true} 
		${true} | ${true} | ${true} | ${false} | ${true} | ${true} | ${true} | ${false} | ${true} | ${true} 
		${true} | ${true} | ${true} | ${false} | ${true} | ${true} | ${true} | ${false} | ${false} | ${true} 
		${true} | ${true} | ${true} | ${false} | ${true} | ${false} | ${true} | ${true} | ${true} | ${true} 
		${true} | ${true} | ${true} | ${false} | ${true} | ${false} | ${true} | ${true} | ${false} | ${true} 
		${true} | ${true} | ${true} | ${false} | ${true} | ${false} | ${true} | ${false} | ${true} | ${true} 
		${true} | ${true} | ${true} | ${false} | ${true} | ${false} | ${true} | ${false} | ${false} | ${true} 
		${true} | ${true} | ${false} | ${true} | ${true} | ${true} | ${true} | ${true} | ${true} | ${true} 
		${true} | ${true} | ${false} | ${true} | ${true} | ${true} | ${true} | ${true} | ${false} | ${true} 
		${true} | ${true} | ${false} | ${true} | ${true} | ${true} | ${true} | ${false} | ${true} | ${true} 
		${true} | ${true} | ${false} | ${true} | ${true} | ${true} | ${true} | ${false} | ${false} | ${true} 
		${true} | ${true} | ${false} | ${true} | ${true} | ${false} | ${true} | ${true} | ${true} | ${true} 
		${true} | ${true} | ${false} | ${true} | ${true} | ${false} | ${true} | ${true} | ${false} | ${true} 
		${true} | ${true} | ${false} | ${true} | ${true} | ${false} | ${true} | ${false} | ${true} | ${true} 
		${true} | ${true} | ${false} | ${true} | ${true} | ${false} | ${true} | ${false} | ${false} | ${true} 
		${true} | ${true} | ${false} | ${false} | ${true} | ${true} | ${true} | ${true} | ${true} | ${true} 
		${true} | ${true} | ${false} | ${false} | ${true} | ${true} | ${true} | ${true} | ${false} | ${true} 
		${true} | ${true} | ${false} | ${false} | ${true} | ${true} | ${true} | ${false} | ${true} | ${true} 
		${true} | ${true} | ${false} | ${false} | ${true} | ${true} | ${true} | ${false} | ${false} | ${true} 
		${true} | ${true} | ${false} | ${false} | ${true} | ${false} | ${true} | ${true} | ${true} | ${true} 
		${true} | ${true} | ${false} | ${false} | ${true} | ${false} | ${true} | ${true} | ${false} | ${true} 
		${true} | ${true} | ${false} | ${false} | ${true} | ${false} | ${true} | ${false} | ${true} | ${true} 
		${true} | ${true} | ${false} | ${false} | ${true} | ${false} | ${true} | ${false} | ${false} | ${true} 
		${false} | ${true} | ${true} | ${true} | ${true} | ${true} | ${true} | ${true} | ${true} | ${true} 
		${false} | ${true} | ${true} | ${true} | ${true} | ${true} | ${true} | ${true} | ${false} | ${true} 
		${false} | ${true} | ${true} | ${true} | ${true} | ${true} | ${true} | ${false} | ${true} | ${true} 
		${false} | ${true} | ${true} | ${true} | ${true} | ${true} | ${true} | ${false} | ${false} | ${true} 
		${false} | ${true} | ${true} | ${true} | ${true} | ${false} | ${true} | ${true} | ${true} | ${true} 
		${false} | ${true} | ${true} | ${true} | ${true} | ${false} | ${true} | ${true} | ${false} | ${true} 
		${false} | ${true} | ${true} | ${true} | ${true} | ${false} | ${true} | ${false} | ${true} | ${true} 
		${false} | ${true} | ${true} | ${true} | ${true} | ${false} | ${true} | ${false} | ${false} | ${true} 
		${false} | ${true} | ${true} | ${false} | ${true} | ${true} | ${true} | ${true} | ${true} | ${true} 
		${false} | ${true} | ${true} | ${false} | ${true} | ${true} | ${true} | ${true} | ${false} | ${true} 
		${false} | ${true} | ${true} | ${false} | ${true} | ${true} | ${true} | ${false} | ${true} | ${true} 
		${false} | ${true} | ${true} | ${false} | ${true} | ${true} | ${true} | ${false} | ${false} | ${true} 
		${false} | ${true} | ${true} | ${false} | ${true} | ${false} | ${true} | ${true} | ${true} | ${true} 
		${false} | ${true} | ${true} | ${false} | ${true} | ${false} | ${true} | ${true} | ${false} | ${true} 
		${false} | ${true} | ${true} | ${false} | ${true} | ${false} | ${true} | ${false} | ${true} | ${true} 
		${false} | ${true} | ${true} | ${false} | ${true} | ${false} | ${true} | ${false} | ${false} | ${true} 
		${false} | ${true} | ${false} | ${true} | ${true} | ${true} | ${true} | ${true} | ${true} | ${true} 
		${false} | ${true} | ${false} | ${true} | ${true} | ${true} | ${true} | ${true} | ${false} | ${true} 
		${false} | ${true} | ${false} | ${true} | ${true} | ${true} | ${true} | ${false} | ${true} | ${true} 
		${false} | ${true} | ${false} | ${true} | ${true} | ${true} | ${true} | ${false} | ${false} | ${true} 
		${false} | ${true} | ${false} | ${true} | ${true} | ${false} | ${true} | ${true} | ${true} | ${true} 
		${false} | ${true} | ${false} | ${true} | ${true} | ${false} | ${true} | ${true} | ${false} | ${true} 
		${false} | ${true} | ${false} | ${true} | ${true} | ${false} | ${true} | ${false} | ${true} | ${true} 
		${false} | ${true} | ${false} | ${true} | ${true} | ${false} | ${true} | ${false} | ${false} | ${true} 
		${false} | ${true} | ${false} | ${false} | ${true} | ${true} | ${true} | ${true} | ${true} | ${true} 
		${false} | ${true} | ${false} | ${false} | ${true} | ${true} | ${true} | ${true} | ${false} | ${true} 
		${false} | ${true} | ${false} | ${false} | ${true} | ${true} | ${true} | ${false} | ${true} | ${true} 
		${false} | ${true} | ${false} | ${false} | ${true} | ${true} | ${true} | ${false} | ${false} | ${true} 
		${false} | ${true} | ${false} | ${false} | ${true} | ${false} | ${true} | ${true} | ${true} | ${true} 
		${false} | ${true} | ${false} | ${false} | ${true} | ${false} | ${true} | ${true} | ${false} | ${true} 
		${false} | ${true} | ${false} | ${false} | ${true} | ${false} | ${true} | ${false} | ${true} | ${true} 
		${false} | ${true} | ${false} | ${false} | ${true} | ${false} | ${true} | ${false} | ${false} | ${true} 
	`('returns $expected when agahnimCheck is $agahnimCheck and agahnim is $agahnim and canDefeatAgahnim is $canDefeatAgahnim and hammer is $hammer and canLiftRocks is $canLiftRocks and moonPearl is $moonPearl and canLiftDarkRocks is $canLiftDarkRocks and canSwim is $canSwim and canAccessDarkWorldPortal is $canAccessDarkWorldPortal.', ({
		agahnimCheck,
		agahnim,
		canDefeatAgahnim,
		hammer,
		canLiftRocks,
		moonPearl,
		canLiftDarkRocks,
		canSwim,
		canAccessDarkWorldPortal,
		expected,
	}) => {
		items.agahnim = agahnim;
		items.hammer = hammer;
		items.moonPearl = moonPearl;

		jest.spyOn(store, 'canLiftRocks', 'get').mockReturnValue(canLiftRocks);
		jest.spyOn(store, 'canLiftDarkRocks', 'get').mockReturnValue(canLiftDarkRocks);
		jest.spyOn(store, 'canSwim', 'get').mockReturnValue(canSwim);
		store.canDefeatAgahnim = jest.fn().mockReturnValue(canDefeatAgahnim);
		store.canAccessDarkWorldPortal = jest.fn().mockReturnValue(canAccessDarkWorldPortal);

		expect(store.canEnterNorthEastDarkWorld(agahnimCheck)).toBe(expected);
	});
});
